theme = "gruvbox"

[editor]
mouse = false
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"

[keys.normal]
"space" = { E = "file_picker_in_current_buffer_directory" }
C-g = ":toggle-option soft-wrap.enable"
C-h = ":toggle-option lsp.display-inlay-hints"
C-r = ":reflow"
