[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "	" }
auto-format = true

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "	" }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
