[[language]]
name = "rust"
indent = { tab-width = 4, unit = "	" }
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }
# config = { checkOnSave = { command = "clippy" } }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "	" }
auto-format = true
